env: "local" # local, dev, prod
http_server:
  port: "8080"
  timeout: 4s
  idle_timeout: 60s
  swagger_enabled: true
database:
  net: "tcp"
  host: "localhost"
  port: "5432"
  db_name: "shopbackend"
  user: "root"
  password: "root"
  sslmode: disable
  time_zone: "UTC"
  timeout: 2s
  max_idle_connections: 40
  max_open_connections: 40
limiter:
  rps: 10
  burst: 20
  ttl: 10m
clients:
  auth_service:
    address: "localhost:44044"
    timeout: 5s
    retries_count: 4
    insecure: true
app_id: 1