// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplateappApiV1 = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/clients": {
            "post": {
                "description": "Регистрация",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Регистрация",
                "parameters": [
                    {
                        "description": "Регистрация",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.clientRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorStruct"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "ErrorStruct": {
            "type": "object",
            "properties": {
                "error_code": {
                    "type": "integer"
                },
                "error_message": {
                    "type": "string"
                }
            }
        },
        "domain.ClientGender": {
            "type": "integer",
            "enum": [
                0,
                10,
                20
            ],
            "x-enum-varnames": [
                "ClientGenderNotSelected",
                "ClientGenderMale",
                "ClientGenderFemale"
            ]
        },
        "v1.clientRegisterRequest": {
            "type": "object",
            "required": [
                "firstname",
                "gender",
                "id",
                "surname"
            ],
            "properties": {
                "birthday": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "gender": {
                    "$ref": "#/definitions/domain.ClientGender"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "surname": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "UserAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfoappApiV1 holds exported Swagger Info so clients can modify it
var SwaggerInfoappApiV1 = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/app/v1",
	Schemes:          []string{},
	Title:            "Backend API",
	Description:      "Backend API for NNBlog Service",
	InfoInstanceName: "appApiV1",
	SwaggerTemplate:  docTemplateappApiV1,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoappApiV1.InstanceName(), SwaggerInfoappApiV1)
}
